language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web sh -c "python3 manage.py test"

before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: 53982ccb-6537-48cf-bd62-4d51807bdc47
  app: fierce-fortress-64893
  on:
    repo: olacodes/movie-backend