version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    # run: python src/manage.py migrate
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build: .
    command: python src/manage.py migrate --noinput
    volumes:
      - .:/app