version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  migration:
    build: .
    command: python manage.py migrate
    depends_on:
      - db
    environment:
      - DEBUG=True

  web:
    build: .
    # run: python src/manage.py migrate
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movie_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PORT=8000
      - DEBUG=True


