# Generated by Django 2.2.7 on 2019-11-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
